### ISSUE TITLE
 remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by MidavSec** [MrDrSushi/SPOPSM#1] opened 2020-11-12 19:56 UTC
Thanks for this project. 
Is there any work around for the 403 error?

 Importing files ...

- Couldn't find the document library 'DCE'
- Something went wrong while trying to upload the files to the 'DCE'.

Ausnahme beim Aufrufen von "ExecuteQuery" mit 0 Argument(en):  "Der Remoteserver hat einen Fehler zurückgegeben: (403) Unzulässig."

ExecuteQuery seems not working.

Thanks.

**Comment by MrDrSushi** [comment] 2020-11-12 20:22
Hi and thanks for your interest on this little project. I'd love to help you but the info you shared above isn't enough, could you please include:

- the command line when you called the PS script
- the CSV input (I guess you could have the issue here, seems to be pointing to a wrong doc library)

**Comment by MidavSec** [comment] 2020-11-13 11:10
.\SPOPSM.ps1 -SiteUrl https://XXXXXXXX.sharepoint.com/sites/DCE -UserName midav@mail.com -CSVFile .\DCE.csv

DCE.csv:
SourceName,SourceFolder,WebSiteName,TargetDocumentLibraryTitle,TargetDocumentLibraryURL
DCE,C:\Temp\DCE,/,DCE,DCE

Error:
===============================
 Processing: DCE  (/sites/DCE)
===============================


- Started at: 11/13/2020 12:07:12

- Checking for Document Library: DCE
- Importing files ...


- Couldn't find the document library 'DCE'
- Something went wrong while trying to upload the files to the 'DCE'.

Ausnahme beim Aufrufen von "ExecuteQuery" mit 0 Argument(en):  "Der Remoteserver hat einen Fehler zurückgegeben: (403) Unzulässig."




      Completed operation for: DCE
                Source Folder: C:\Temp\DCE
                      WebSite: /sites/DCE
             Document Library: DCE

                  Total Files: 0
                Total Folders: 0

               Files Failures: 0
             Folders Failures: 0

                Files Renamed: 0
              Folders Renamed: 0

                Files Skipped: 0

       Operation completed at: 13.11.2020 12:07:12
             Total time spent: 00:00:00

Sharepoint Screenshot:
https://pasteboard.co/JA9WLh0.png

Thank you!

**Comment by MrDrSushi** [comment] 2020-11-13 22:55
Thanks for the info, I'm going to recreate the same input from your example above and see what happens on my side, apparently the parameters and CSV input are all correct, I can't see any issues. Let me try and I will post back my findings.

**Comment by MidavSec** [comment] 2020-11-18 14:44
MrDrSushi, will be there any update in the next days? When not I would search for alternatives. Thank you very much in advance.

**Comment by MrDrSushi** [comment] 2020-11-19 00:48
New version available!

Apparently all the issues around HTTP 403 were caused by updates from Microsoft on their libraries and authentication methods for CSOM, there were several changes to the script but the major was:

`$CSOM_context.AuthenticationMode = [Microsoft.SharePoint.Client.ClientAuthenticationMode]::Default`

This new version also includes **-UseMFA** parameter, it provides a better support for MFA authentication, you may want to check this while trying the newest version in case you are using or plan to incorporate MFA into your script.

Remember to run the SPOPSM.ps1 under a SharePoint Online Management Shell session to avoid any issues.

If all the script fixes work for you, please close the issue.

**Closed as completed** 2020-11-19 21:51 UTC
